name: Laravel Deployment Workflow
on:
  push:
    branches: [ main, master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy via Rsync
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          rsync -avz \
            --delete \
            --exclude '.git*' \
            --exclude 'node_modules/' \
            --exclude 'vendor/' \
            --exclude 'composer.json' \
            --exclude 'composer.lock' \
            --exclude 'storage/*.log' \
            --exclude 'storage/*/token.json' \
            --exclude 'storage/*/credentials.json' \
            --exclude 'storage/oauth-private.key' \
            --exclude 'storage/oauth-public.key' \
            --exclude 'storage/logs/' \
            --exclude 'bootstrap/cache/' \
            --exclude 'storage/framework/cache/' \
            --exclude 'storage/framework/sessions/' \
            --exclude 'storage/framework/views/' \
            --exclude 'modules_statuses.json' \
            --exclude '.env*' \
            -e "sshpass -p '$SSH_PASSWORD' ssh -o StrictHostKeyChecking=no" \
            ./ \
            root@s1.juvo.app:/var/www/fastuser/data/www/slingbolt.com/